![image.png](https://static.poder360.com.br/uploads/2024/08/NFL-Logo-848x477.jpg)

# <span style="color: #0d69c5">Tratamento de Dados da NFL de 2009 a 2017</span>

#### <span style="color: #8bc0f5">Sobre o database</span>

O dataset **NFL Play by Play 2009-2017 (v4)**, disponível no Kaggle, reúne o registro de todas as jogadas da NFL em nove temporadas. Cada linha representa uma jogada, totalizando cerca de **450 mil registros e 100 colunas**, que cobrem contexto do jogo (times, quarto, down, distância), jogadores envolvidos, resultados, penalidades e métricas de probabilidade de pontos e vitória (como EPA e Win Probability).

#### <span style="color: #8bc0f5">Objetivo da atividade</span>

Construir um pipeline completo de **qualidade e armazenamento**: diagnosticar a estrutura e os problemas do dataset, corrigir a tipificação, tratar valores ausentes e inconsistências com decisões justificadas, e exportar o resultado em formato Parquet. Ao final, compara-se o tamanho com o CSV original, valida-se que os dados foram preservados e resume-se as melhorias obtidas em **consistência, confiabilidade e eficiência de armazenamento.**

### <span style="color: #8bc0f5">Carregamento de bibliotecas e database</span>

Nessa etapa realizamos o carregamento do Banco de Dados. Também realizamos a importação das bibliotecas necessárias para análise exploratória dos dados.

Bibliotecas Essenciais
- 🐼 Pandas
- 🔢 Numpy
- 📖 KaggleHub
- 💻 OS

In [ ]:
#%pip install kagglehub

In [3]:
# Manipulação dos dados
import pandas as pd # Dataframe
import numpy as np # Operações
import os
import kagglehub
from kagglehub import KaggleDatasetAdapter

c:\Users\48694260808\AppData\Local\Programs\Python\Python314\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [4]:
# Download doataset do KaggleHub
root = kagglehub.dataset_download("maxhorowitz/nflplaybyplay2009to2016") 
print("Root:", root)

Root: C:\Users\48694260808\.cache\kagglehub\datasets\maxhorowitz\nflplaybyplay2009to2016\versions\6

In [5]:
# Criar caminho para o arquivo CSV 
csv_path = os.path.join(root, "NFL Play by Play 2009-2017 (v4).csv") 

# Carrega o arquivo CSV em um DataFrame
df = pd.read_csv(csv_path) 
df.head()

C:\Users\48694260808\AppData\Local\Temp\ipykernel_15280\1156612853.py:5: DtypeWarning: Columns (0: DefTwoPoint, 1: BlockingPlayer) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv_path)

,Date,GameID,Drive,qtr,down,time,TimeUnder,TimeSecs,PlayTimeDiff,SideofField,...,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
0,2009-09-10,2009091000,1,1,NaN,15:00,15,3600.0,0.0,TEN,...,NaN,0.485675,0.514325,0.546433,0.453567,0.485675,0.060758,NaN,NaN,2009
1,2009-09-10,2009091000,1,1,1.0,14:53,15,3593.0,7.0,PIT,...,1.146076,0.546433,0.453567,0.551088,0.448912,0.546433,0.004655,-0.032244,0.036899,2009
2,2009-09-10,2009091000,1,1,2.0,14:16,15,3556.0,37.0,PIT,...,NaN,0.551088,0.448912,0.510793,0.489207,0.551088,-0.040295,NaN,NaN,2009
3,2009-09-10,2009091000,1,1,3.0,13:35,14,3515.0,41.0,PIT,...,-5.031425,0.510793,0.489207,0.461217,0.538783,0.510793,-0.049576,0.106663,-0.156239,2009
4,2009-09-10,2009091000,1,1,4.0,13:27,14,3507.0,8.0,PIT,...,NaN,0.461217,0.538783,0.558929,0.441071,0.461217,0.097712,NaN,NaN,2009

#### <span style="color: #8bc0f5">Diagnóstico de Dados</span>

In [10]:
# Dimensões de Linhas X Colunas
df.shape

(407688, 102)

In [11]:
# Visualização de linhas aleatórias do DataFrame
df.sample(5)

,Date,GameID,Drive,qtr,down,time,TimeUnder,TimeSecs,PlayTimeDiff,SideofField,...,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
25381,2009-11-22,2009112200,14,3,1.0,07:35,8,1355.0,48.0,IND,...,NaN,0.519395,0.480605,0.547420,0.452580,0.519395,0.028025,NaN,NaN,2009
374106,2017-10-08,2017100802,23,4,3.0,03:28,4,208.0,4.0,CAR,...,2.188750,0.131368,0.868632,0.322814,0.677186,0.131368,0.191445,0.077674,0.113771,2017
81188,2010-12-19,2010121900,4,1,2.0,02:05,3,2825.0,31.0,KC,...,NaN,0.627818,0.372182,0.681035,0.318965,0.372182,-0.053217,NaN,NaN,2010
8321,2009-10-04,2009100400,1,1,1.0,14:55,15,3595.0,5.0,DET,...,0.561958,0.493982,0.506018,0.393797,0.606203,0.506018,0.100185,0.079984,0.020201,2009
319837,2016-09-18,2016091800,17,3,1.0,09:21,10,1461.0,48.0,SF,...,NaN,0.643396,0.356604,0.629743,0.370257,0.643396,-0.013653,NaN,NaN,2016

In [12]:
# Analisando Tipo de Dados das colunas 
df.dtypes

Date            str
GameID        int64
Drive         int64
qtr           int64
down        float64
             ...
Win_Prob    float64
WPA         float64
airWPA      float64
yacWPA      float64
Season        int64
Length: 102, dtype: object

In [16]:
# Uso total da memória inicial em MB
memoria_inicial = df.memory_usage(deep=True).sum() / (1024 ** 2)
print(f"Uso total da memória inicial: {memoria_inicial:.2f} MB")

Uso total da memória inicial: 380.54 MB